# $schema: http://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@e71834aa34fcde4d7d315965ddd17e78af94140d

  verify-mkdocs:
    uses: harmelodic/workflows/.github/workflows/verify-mkdocs.yaml@e71834aa34fcde4d7d315965ddd17e78af94140d
  release-mkdocs:
    needs: verify-mkdocs
    uses: harmelodic/workflows/.github/workflows/release-mkdocs.yaml@e71834aa34fcde4d7d315965ddd17e78af94140d
